### ISSUE TITLE
"Failed to import any qt binding"

### ISSUE THREAD

**Issue by olaims** [amosborne/dorfperfekt#1]
Hello,

I have installed Python 3.9 from the official website. 

I've followed the two commands,
```
pip install dorfperfekt
dorfperfekt
```

The pip install dorfperfekt shows that all requirements are already satisfied.

But then I get the following error,

```
\dorfperfekt-main> dorfperfekt
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\Scripts\dorfperfekt.exe\__main__.py", line 4, in <module>
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\dorfperfekt\__main__.py", line 6, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\qt_compat.py", line 142, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

Before I tried using Python 3.10 but the same error was coming.

**Comment by amosborne** [comment]
Would you please try running the following from command line: `QT_API=pyside6 dorfperfekt`

**Comment by olaims** [comment]
Same error after `pip install --upgrade dorfperfekt`

When I run `QT_API=pyside6 dorfperfekt` I get 
```
'QT_API' is not recognized as an internal or external command,
operable program or batch file.
```

- Operating system: Windows 10
- Python version (eg. 3.9.x): Python 3.10
- Matplotlib version: 3.5.2
- Pyside6 version: 6.3.0

**Comment by olaims** [comment]
I've created the environment variable `QT_API=pyside6`
Now I get 
```
    raise ImportError(str(shiboken6) + ' does not exist')
ImportError: C:\Users\****\AppData\Local\Programs\Python\Python310\Lib\shiboken6\libshiboken does not exist
```

**Comment by olaims** [comment]
Interesting, I just ran
`>pip install --force-reinstall pyside6`
And now it starts :)

I guess that together with the env variable was the problem :)

**Comment by olaims** [comment]
environment variable QT_API=pyside6 +  `pip install --force-reinstall pyside6` solved the issue
